# Name of our action
name: "Chromatic"
# The event that will trigger the action
on: push

# What the action will do
jobs:
  chromatic-deployment:
    # The operating system it will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./storybook/learnstorybook-design-system
    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/design-systems-for-developers/react/en/review/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: ./storybook/learnstorybook-design-system
