supergraph:
  listen: 127.0.0.1:5000

telemetry:
  instrumentation:
    spans:
      mode: spec_compliant

headers:
  all:
    request:
      - propagate:
          matching: .*

cors:
  origins:
    - http://localhost:3000
