federation_version: =2.8.1
subgraphs:
  locations:
    routing_url: http://localhost:4001
    schema:
      file: ../subgraph-locations/locations.graphql
  reviews:
    routing_url: http://localhost:4002
    schema:
      file: ../subgraph-reviews/reviews.graphql
